name: Android CI

on:
  push:
    branches: [ "rystars" ]
  pull_request:
    branches: [ "rystars" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'GraalVM'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
